

MESSAGE_PROTO = {'hostfqdn': 'mahmoud-gabbro',
                 'hostname': 'mahmoud-gabbro',
                 'linux_dist': {'name': 'Ubuntu', 'version': '14.04'},
                 'python': {'argv': 'collect.py --verbose',
                            'bin': '/usr/bin/python',
                            'build_date': 'Jun 22 2015 17:58:13',
                            'compiler': 'GCC 4.8.2',
                            'have_readline': True,
                            'have_ucs4': True,
                            'is_64bit': True,
                            'openssl_version': 'OpenSSL 1.0.1f 6 Jan 2014',
                            'sqlite_version': '3.8.2',
                            'version': '2.7.6 (default, Jun 22 2015, 17:58:13) \n[GCC 4.8.2]',
                            'version_info': [2, 7, 6, 'final', 0]},
                 'time': {'std_utc_offset': -8.0, 'utc': '2016-04-20 09:24:05.190536'},
                 'uname': {'machine': 'x86_64',
                           'node': 'mahmoud-gabbro',
                           'processor': 'x86_64',
                           'release': '3.13.0-85-generic',
                           'system': 'Linux',
                           'version': '#129-Ubuntu SMP Thu Mar 17 20:50:15 UTC 2016'},
                 'username': 'mahmoud',
                 'uuid': 'c4d41ca1-1854-4911-97d6-a1b6b5ed1444'}
